Repository smaranjitghose/doc2pen, pull requests merged in 2020-08, with the labels that each got.

#39 Added Patreon & Buymeacoffee
  assets/css/contact.css
  assets/images/Patreon.webp
  contact.html
Labels: PR: unreviewed

#40 Issue #10 Solved
  assets/css/custom.css
  assets/js/script.js
  editor.html
Labels: PR: unreviewed, enhancement, hackincodes20

#42 Enhancement of characters limit to 10k.
  assets/js/script.js
Labels: PR: unreviewed, enhancement, hackincodes20

#43 Revert "Enhancement of characters limit to 10k."
  assets/js/script.js
Labels: PR: unreviewed

#44 Revert "Issue #10 Solved"
  assets/css/custom.css
  assets/js/script.js
  editor.html
Labels: PR: unreviewed

#45 Complete responsive Homepage
  assets/css/style.css
  index.html
Labels: PR: unreviewed

#51 Added Cards to the Homepage
  assets/css/style.css
  assets/images/contact_open_source_license1.svg
  index.html
Labels: PR: unreviewed, psoc2020

#53 Text is visible in both themes
  assets/css/custom.css
  assets/css/style.css
Labels: PR: unreviewed, bug, psoc2020

#55 corrected contact page
  assets/css/contact.css
  contact.html
Labels: PR: unreviewed, psoc2020

#52 added footer
  assets/css/footer.css
  assets/css/materialize.min.css
  assets/css/style.css
  index.html
Labels: CH-20, PR: unreviewed

#68 Responsiveness of card modified a little bit
  assets/css/contact.css
  assets/css/style.css
  contact.html
  index.html
Labels: CH-20, PR: unreviewed

#72 Logo Closes #58
  assets/css/navigation.css
  assets/fonts/KaushanScript-Regular.otf
  contact.html
  editor.html
  index.html
Labels: PR: unreviewed

#71 Sponsorship
  .vscode/settings.json
  assets/css/contact.css
  contact.html
Labels: PR: unreviewed

#73 Solved #70: Added 404 page
  404.html
  assets/css/style_404.css
Labels: PR: unreviewed

#87 Solved #80 : Moving JS code from index.html to separate .js file in assets
  assets/js/materialize.min.js
  assets/js/script.js
  index.html
Labels: PR: unreviewed

#82 changes made in contibutors section
  assets/css/contact.css
  assets/images/resized_images/resize_sonali.png
  assets/images/resized_images/resized_am.png
  assets/images/resized_images/resized_shi.png
  assets/images/resized_images/resized_v2.png
  contact.html
Labels: CH-20, Medium, PR: reviewed-changes-requested, enhancement

#94 resolved and beautifies code
  assets/js/script.js
  editor.html
Labels: CH-20, Easy, enhancement

#96 Added 7 new pages to switch between them
  assets/images/pages/page (0).jpg
  assets/images/pages/page (1).jpg
  assets/images/pages/page (2).jpg
  assets/images/pages/page (3).jpg
  assets/images/pages/page (4).jpg
  assets/images/pages/page (5).jpg
  assets/images/pages/page (6).jpg
  assets/images/pages/page (7).jpg
  assets/js/script.js
  assets/js/sketch.js
  editor.html
Labels: CH-20, Easy, enhancement

#90 Improved card structure
  assets/css/style.css
  index.html
Labels: CH-20, Easy, enhancement

#99 #62 added meta tags by using open graph
  contact.html
  editor.html
  index.html
Labels: CH-20, Easy, PR: unreviewed

#102 #62 Keywords added
  contact.html
  editor.html
  index.html
Labels: CH-20, Easy, PR: partially-approved, PR: unreviewed

#113 Added different color feature
  404.html
  assets/css/style.css
  assets/js/sketch.js
  editor.html
  index.html
Labels: CH-20, Easy, enhancement

#121 Added 2 new colours
  assets/js/sketch.js
  editor.html
Labels: PR: unreviewed

#101 2 sided view of editor and Aesthetics of the page (Issue #60)
  assets/css/custom.css
  assets/css/editor.css
  assets/js/script.js
  assets/js/sketch.js
  editor.html
Labels: CH-20, Medium
