Repository smaranjitghose/doc2pen, pull requests merged in 2020-12, with the labels that each got.

#287 fixes ☑ minor mistake at readme ✒😏
  README.md
Labels: PR: unreviewed

#292 New dropdown for FontSize menu item
  assets/js/editor.js
  editor.html
Labels: DWOC2020

#291 download options added
  assets/css/editor.css
  editor.html
Labels: PR: unreviewed

#294 Styled the nav-items on hovering over them
  assets/css/style.css
  assets/js/main.js
Labels: DWOC, Level-4

#295 Converted I-Beam Pointer to Link Pointer
  editor.html
Labels: DWOC, Level-3

#296 Revert "Converted I-Beam Pointer to Link Pointer"
  editor.html
Labels: PR: unreviewed

#289 Update editor.html
  editor.html
Labels: DWOC, Level-3

#286 navbar hover effect added
  assets/css/style.css
Labels: DWOC, PR: reviewed-changes-requested

#305 Implementation of maps in homepage
  assets/css/style.css
  index.html
Labels: DWOC, Level-4

#306 Open Source cards updated
  assets/images/events/SWOC-logo.png
  assets/images/events/woc-logo.png
  assets/js/main.js
Labels: DWOC, Level-3

#313 updated the style.css #304
  assets/css/style.css
  assets/js/main.js
Labels: DWOC, Level-3

#312 added margin dropdown menu
  assets/js/editor.js
  editor.html
Labels: DWOC, PR: reviewed-approved

#308 [issue #300]: Created responsive menubar for all adjustment sliders
  assets/css/editor.css
  assets/css/style.css
  assets/js/editor.js
  editor.html
Labels: DWOC, Level-4
