Repository smaranjitghose/doc2pen, pull requests merged in 2020-07, with the labels that each got.

#11 Add fonts
  fonts/AnnieUseYourTelescope-Regular.ttf
  fonts/font (10).ttf
  fonts/font (11).ttf
  fonts/font (12).ttf
  fonts/font (13).ttf
  fonts/font (14).ttf
  fonts/font (15).ttf
  fonts/font (16).ttf
  fonts/font (17).ttf
  fonts/font (18).ttf
  fonts/font (19).ttf
  fonts/font (20).ttf
  fonts/font (21).ttf
  fonts/font (8).ttf
  fonts/font (9).ttf
Labels: PR: unreviewed

#12 About page added and modified navbar
  about.html
  index.html
Labels: PR: unreviewed

#16 Landing page
  assets/css/style.css
  assets/images/bg.png
  assets/images/bgfront.jpg
  landingpage.html
Labels: PR: unreviewed

#17 Landing page redirected to main page
  landingpage.html
Labels: PR: unreviewed

#18 theme_changer_added_by_Varun-28
  assets/css/custom.css
  assets/js/script.js
  index.html
Labels: PR: unreviewed

#26 Updations done in splashscreen
  about.html
  assets/css/custom.css
  assets/css/style.css
  assets/images/bg.png
  assets/images/bgfront.jpg
  assets/js/splashscript.js
  index.html
  landingpage.html
  splashscreen.html
Labels: psoc2020

#28 splash changed
  kelly-sikkema-vtKc7BpJ-vU-unsplash.jpg
  splash.css
  splash.html
Labels: PR: unreviewed, psoc2020

#33 contact page
  assets/css/style.css
  assets/images/a2.png
  assets/images/anush.jfif
  assets/images/shi2.png
  assets/images/smaran.png
  assets/images/sonali2.png
  assets/images/undraw_content_team_3epn(1).svg
  assets/images/v2.png
  contact.html
Labels: PR: unreviewed

#34 Revert "contact page"
  assets/css/style.css
  assets/images/a2.png
  assets/images/anush.jfif
  assets/images/shi2.png
  assets/images/smaran.png
  assets/images/sonali2.png
  assets/images/undraw_content_team_3epn(1).svg
  assets/images/v2.png
  contact.html
Labels: PR: unreviewed

#35 Contact Page contents are added
  assets/css/contact.css
  assets/images/a2.png
  assets/images/anush.jfif
  assets/images/github.svg
  assets/images/linkedin.svg
  assets/images/shi2.png
  assets/images/smaran.png
  assets/images/sonali2.png
  assets/images/undraw_content_team_3epn(1).svg
  assets/images/v2.png
  contact.html
Labels: PR: unreviewed, psoc2020

#37 Maded home page Responsive
  assets/css/style.css
  index.html
Labels: PR: unreviewed, psoc2020
