Repository smaranjitghose/doc2pen, pull requests merged in 2020-10, with the labels that each got.

#214 navbar bug fix
  assets/js/main.js
Labels: CH-20, Easy, Hacktoberfest, bug

#213 Fix the Sidenav to be Opened
  index.html
Labels: Beginner, CH-20, Hacktoberfest, bug

#212 Fixed broken images and links
  README.md
  assets/images/hakin_codes.png
  assets/images/psoc_logo.png
  assets/js/main.js
  index.html
Labels: Beginner, CH-20, bug

#208 added word count feature
  assets/css/editor.css
  assets/js/editor.js
  assets/js/script.js
  assets/js/sketch.js
  editor.html
Labels: CH-20, Easy, Hacktoberfest

#220 solved #181 added : favicon
  assets/images/favicon.png
  editor.html
  index.html
Labels: Beginner, CH-20, Hacktoberfest

#217 removed materialize
  assets/css/editor.css
  assets/css/style.css
  assets/js/main.js
  editor.html
  index.html
Labels: CH-20, Hacktoberfest, Hard

#223 project maintainer details loaded from main.js
  assets/js/main.js
  index.html
Labels: CH-20, Easy, Hacktoberfest

#224 commit on scroll behaviour and button locations
  assets/css/style.css
  assets/js/main.js
Labels: CH-20, Easy, Hacktoberfest, bug, enhancement

#226 Updated README CH20 Hacktoberfest
  README.md
Labels: CH-20, Easy, Hacktoberfest

#228 dynamic details and centered cards
  assets/js/main.js
  index.html
Labels: CH-20, Easy, Hacktoberfest

#227 Made the editor responsive
  assets/css/editor.css
  assets/js/editor.js
  editor.html
Labels: CH-20, Hacktoberfest, Medium

#233 Major Bugs in Home page
  assets/css/style.css
  assets/js/main.js
  index.html
Labels: CH-20, Easy, Hacktoberfest

#232 nav and footer colors
  assets/css/editor.css
  assets/css/style.css
Labels: CH-20, Hacktoberfest, Medium

#235 Bug in the alignment of contributor section
  assets/css/style.css
  index.html
Labels: CH-20, Easy, Hacktoberfest

#231 Solved #194: added Poppins font to the editor and added scroll to the font selection menu
  assets/css/editor.css
  assets/fonts/font (14).ttf
  assets/js/editor.js
  editor.html
Labels: CH-20, Easy, Hacktoberfest

#236 range field value display
  assets/css/editor.css
  assets/js/editor.js
  editor.html
Labels: CH-20, Easy

#237 Colors added accordingly
  assets/css/style.css
Labels: CH-20, Easy, Hacktoberfest

#240 Added Open Source and resolved all issues
  assets/css/style.css
  assets/images/SLOP.png
  index.html
Labels: CH-20, Hacktoberfest, Medium

#238 resized cards and font
  assets/css/editor.css
  assets/css/style.css
  assets/js/main.js
  editor.html
  index.html
Labels: CH-20, Hacktoberfest, Hard

#244 Open source section added (enhancement)
  assets/css/style.css
  index.html
Labels: CH-20, Hacktoberfest, Medium

#247 Open Source section enhancement (as mentioned)
  assets/css/style.css
  assets/js/main.js
  index.html
Labels: CH-20, Hacktoberfest, Medium

#249 solved #180 solved : reorder assets
  assets/images/about/download.svg
  assets/images/about/fonts.svg
  assets/images/about/open-source.svg
  assets/images/about/page.svg
  assets/images/about/typing.svg
  assets/images/events/SLOP.png
  assets/images/events/hakin_codes.png
  assets/images/events/psoc_logo.png
  assets/images/team/anush_bhatia.png
  assets/images/team/smaranjit_ghose.png
  assets/js/main.js
  index.html
Labels: Hacktoberfest

#252 Added font-size select button in nav-bar
  assets/css/editor.css
  assets/js/editor.js
  editor.html
Labels: hacktoberfest-accepted

#253 Fixed "Team members profile pictures were not showing"
  assets/css/style.css
Labels: hacktoberfest-accepted

#254 Updated contributors information
  assets/images/contributors/24.jpg
  assets/js/main.js
Labels: hacktoberfest-accepted

#257 Made axes functional
  assets/js/editor.js
  editor.html
Labels: hacktoberfest-accepted

#258 Made Font Size Functional
  assets/js/editor.js
  editor.html
Labels: hacktoberfest-accepted

#259 Update editor.js
  assets/js/editor.js
Labels: hacktoberfest-accepted

#260 Update editor.html
  editor.html
Labels: hacktoberfest-accepted

#262 Improved the Menubar UI
  assets/css/editor.css
  assets/js/editor.js
  assets/js/main.js
Labels: hacktoberfest-accepted

#265 option to upload txt file in Menubar
  .DS_Store
  assets/.DS_Store
  editor.html
Labels: PR: partially-approved, hacktoberfest-accepted

#264 Changed contact form UI
  assets/css/style.css
  assets/js/main.js
  index.html
Labels: hacktoberfest-accepted

#279 Fixed download button bug
  editor.html
Labels: hacktoberfest-accepted

#280 Fixed word count was not updating
  assets/js/editor.js
Labels: hacktoberfest-accepted

#277 favicon.png updated
  assets/images/favicon.png
  assets/js/main.js
Labels: hacktoberfest-accepted

#281 Background overflow bug
  assets/css/editor.css
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted

#283 Update README.md
  README.md
Labels: hacktoberfest-accepted
