Repository smaranjitghose/doc2pen, pull requests merged in 2020-09, with the labels that each got.

#122 Added 7 fonts
  assets/fonts/KaushanScript-Regular.otf
  assets/fonts/font (10).ttf
  assets/fonts/font (11).ttf
  assets/fonts/font (12).ttf
  assets/fonts/font (13).ttf
  assets/fonts/font (7).ttf
  assets/fonts/font (8).ttf
  assets/fonts/font (9).ttf
  assets/js/sketch.js
  editor.html
Labels: CH-20, Easy, PR: unreviewed, enhancement

#125 Menubar improved
  assets/css/custom.css
  assets/js/sketch.js
  editor.html
Labels: PR: unreviewed

#129 contibutors added
  assets/images/resized_images/1.jpg
  assets/images/resized_images/10.png
  assets/images/resized_images/11.jpg
  assets/images/resized_images/12.jpg
  assets/images/resized_images/2.png
  assets/images/resized_images/3.jpg
  assets/images/resized_images/4.png
  assets/images/resized_images/5.jpg
  assets/images/resized_images/6.png
  assets/images/resized_images/7.jpg
  assets/images/resized_images/8.jpg
  assets/images/resized_images/9.jpg
  team.html
Labels: CH-20, Easy

#131 Update Design of Homepage
  assets/css/style.css
  assets/js/video.js
  index.html
Labels: CH-20, Easy

#138 Dynamic Navbar added using materialize css
  assets/css/style.css
  assets/js/main.js
  index.html
Labels: CH-20, Easy

#140 Logo added
  assets/css/style.css
  assets/images/logo.png
  assets/js/main.js
Labels: CH-20, Easy, PR: partially-approved, PR: unreviewed

#141 Update README.md
  README.md
Labels: Beginner, CH-20, ReadMe, bug, documentation

#142 Revert "Menubar improved"
  assets/css/custom.css
  assets/js/sketch.js
  editor.html
Labels: PR: unreviewed

#144 Added : wave footer
  assets/css/style.css
  assets/js/main.js
  index.html
Labels: CH-20, Easy

#145 Responsive contact page added
  assets/css/style.css
  assets/images/contact.jpg
  assets/js/main.js
  index.html
Labels: CH-20, Easy

#146 Added map (using API) and captcha field
  assets/css/style.css
  assets/js/main.js
  index.html
Labels: CH-20, Medium

#148 added team section
  assets/css/team.css
  assets/images/anush_bhatia.png
  assets/images/github.svg
  assets/images/linkedin.svg
  assets/images/smaranjit_ghose.png
  assets/js/main.js
  assets/resized_images/1.jpg
  assets/resized_images/10.png
  assets/resized_images/11.jpg
  assets/resized_images/12.jpg
  assets/resized_images/2.png
  assets/resized_images/3.jpg
  assets/resized_images/4.png
  assets/resized_images/5.jpg
  assets/resized_images/6.png
  assets/resized_images/7.jpg
  assets/resized_images/8.jpg
  assets/resized_images/9.jpg
  assets/resized_images/resize_sonali.png
  assets/resized_images/resized_am.png
  assets/resized_images/resized_shi.png
  assets/resized_images/resized_v2.png
  index.html
  team.html
Labels: CH-20, Easy

#150 reorder team section and contact from
  index.html
Labels: Beginner, CH-20

#154 Team page section added
  assets/css/style.css
  assets/images/smaranjit_ghose.png
  index.html
Labels: CH-20, Medium

#157 Contributors section added
  assets/css/style.css
  index.html
Labels: CH-20, Easy

#158 Revert "Contributors section added"
  assets/css/style.css
  index.html
Labels: PR: unreviewed

#159 Added About Section CH20
  assets/css/style.css
  assets/images/download.svg
  assets/images/fonts.svg
  assets/images/open-source.svg
  assets/images/page.svg
  assets/images/typing.svg
  index.html
Labels: CH-20, Medium

#161 Contributor section added
  assets/css/style.css
  index.html
Labels: CH-20, Easy

#162 Injected the contributor section, added github icon and bug in link button
  assets/css/style.css
  assets/js/main.js
  index.html
Labels: CH-20, Easy

#163 Contributors profile added
  assets/css/style.css
  assets/images/contributors/1.jpg
  assets/images/contributors/10.png
  assets/images/contributors/11.png
  assets/images/contributors/12.jpg
  assets/images/contributors/13.jpg
  assets/images/contributors/14.png
  assets/images/contributors/15.jpg
  assets/images/contributors/2.jpg
  assets/images/contributors/3.jpg
  assets/images/contributors/4.jpg
  assets/images/contributors/5.jpg
  assets/images/contributors/6.png
  assets/images/contributors/7.jpg
  assets/images/contributors/8.png
  assets/images/contributors/9.jpg
  assets/js/main.js
Labels: CH-20, Easy

#164 nav and about section
  assets/css/style.css
  assets/js/main.js
  index.html
Labels: CH-20, Easy

#165 About section bug
  assets/css/style.css
  index.html
Labels: Beginner, CH-20

#166 Contributors section completed
  assets/images/contributors/1.jpeg
  assets/images/contributors/1.jpg
  assets/images/contributors/16.jpg
  assets/images/contributors/17.jpg
  assets/images/contributors/18.jpg
  assets/images/contributors/19.jpg
  assets/images/contributors/20.jpg
  assets/images/contributors/21.jpg
  assets/images/contributors/22.jpg
  assets/js/main.js
Labels: Beginner, CH-20, PR: unreviewed

#168 Added Home Section CH20
  assets/css/style.css
  assets/css/wave_image/wave.png
  assets/images/title-image.svg
  index.html
Labels: CH-20, Easy

#169 Revert "Added Home Section CH20"
  assets/css/style.css
  assets/css/wave_image/wave.png
  assets/images/title-image.svg
  index.html
Labels: PR: unreviewed

#170 Added Home Section Again Ch20
  assets/css/style.css
  assets/css/wave-image/wave.png
  assets/images/title-image.svg
  index.html
Labels: CH-20, Medium

#172 Modified Footer CH20
  assets/css/style.css
  assets/js/main.js
Labels: CH-20, Easy

#173 First section bug and button added
  assets/css/style.css
  assets/images/contributors/23.jpg
  assets/js/main.js
  index.html
Labels: CH-20, Easy

#174 Minor bugs
  assets/css/style.css
Labels: Beginner, CH-20

#171 editor page
  assets/css/editor.css
  assets/css/style.css
  assets/fonts/font (0).ttf
  assets/fonts/font (1).ttf
  assets/fonts/font (10).ttf
  assets/fonts/font (11).ttf
  assets/fonts/font (12).ttf
  assets/fonts/font (13).ttf
  assets/fonts/font (2).ttf
  assets/fonts/font (3).ttf
  assets/fonts/font (4).ttf
  assets/fonts/font (5).ttf
  assets/fonts/font (6).ttf
  assets/fonts/font (7).ttf
  assets/fonts/font (8).ttf
  assets/fonts/font (9).ttf
  assets/images/pages/page (0).jpg
  assets/images/pages/page (1).jpg
  assets/images/pages/page (2).jpg
  assets/images/pages/page (3).jpg
  assets/images/pages/page (4).jpg
  assets/images/pages/page (5).jpg
  assets/images/pages/page (6).jpg
  assets/images/pages/page (7).jpg
  assets/js/editor.js
  assets/js/jquery.js
  assets/js/main.js
  assets/js/materialize.min.js
  assets/js/script.js
  editor.html
  index.html
Labels: CH-20, Medium

#202 added link for check out button
  index.html
Labels: Beginner, CH-20

#203 Contributors.
  assets/js/main.js
Labels: Beginner, CH-20

#210 fixed blue color and added option of golden color
  assets/js/editor.js
  editor.html
Labels: Hacktoberfest
