Repository smaranjitghose/doc2pen, pull requests merged in 2021-06, with the labels that each got.

#1036 Bug Fix: color picker wont close after selecting a single color. colors can be selected while dragging on the palette
  package-lock.json
  package.json
  src/components/Dropdown/Dropdown.jsx
  src/pages/Sketch/components/Toolbox/Toolbox.jsx
  src/pages/Sketch/components/Toolbox/toolbox.module.scss
  yarn.lock
Labels: Level3, PR: reviewed-approved, gssoc21

#1038 Bug Fix: PDF files can only be merged, other format options should not show in Output dropdown
  src/pages/MediaManip/DragDrop/DragDrop.jsx
Labels: Level2, PR: reviewed-approved, gssoc21

#1023 Set up Pre-Commit Hooks
  netlify.toml
  package.json
  yarn.lock
Labels: PR: unreviewed, gssoc21, merge-conflict

#1045 2 UI fixes + Useless code/file removal
  netlify.toml
  public/_redirects
  src/components/Header/header.module.scss
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.jsx
  src/pages/Editor/sections/OutputComponent/output.module.scss
  src/pages/Home/sections/Team/components/FluidCard/FluidCard.jsx
  src/pages/Sketch/components/Canvas.jsx
Labels: Level3, gssoc21

#1040 New map features
  src/pages/Home/sections/Contact/components/Map/Map.jsx
  src/pages/Home/sections/Contact/components/Map/map.scss
Labels: PR: unreviewed, gssoc21

#1034 draggable undo redo button in sketch page
  package.json
  src/pages/Sketch/components/Canvas.jsx
  src/pages/Sketch/components/canvas.module.scss
  yarn.lock
Labels: PR: unreviewed, gssoc21

#1037 Bug fix sketch page crosshair does not coincide with drawn point
  CODE_OF_CONDUCT.md
  src/pages/Home/sections/Contact/components/EmojiRating/EmojiRating.jsx
  src/pages/Sketch/components/Canvas.jsx
  src/pages/Sketch/components/Toolbox/Toolbox.jsx
  src/pages/Sketch/components/Toolbox/toolbox.module.scss
  src/pages/Sketch/components/canvas.module.scss
  src/pages/Sketch/sketch.module.scss
Labels: PR: unreviewed

#929 Icon Searchbox@sketch
  src/pages/Sketch/components/IconLibrary/IconsLibrary.jsx
  src/pages/Sketch/components/IconLibrary/icon-lib.module.scss
  src/pages/Sketch/components/IconLibrary/icon-pack1/json-bw.svg
Labels: PR: unreviewed, deprecated

#1064 fix: colorPicker popup's z-index
  src/pages/Sketch/components/Toolbox/toolbox.module.scss
Labels: LGMSOC21, PR: reviewed-approved, 🟨 Level2

#1065 User sent to fresh new page upon contact form submission without Backend
  .eslintrc.js
  package-lock.json
  src/pages/Home/sections/Contact/components/ExperienceForm/ExperienceForm.jsx
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#1068 Added MetaComponent and metadata for media manip
  src/pages/MediaManip/MediaManip.jsx
  src/seo/metaData.js
Labels: LGMSOC21, PR: reviewed-approved, 🟨 Level2
