Repository smaranjitghose/doc2pen, pull requests merged in 2021-04, with the labels that each got.

#819 Changed line-spacing step from 1 to 0.1
  src/pages/Editor/sections/Settings/Settings.js
Labels: Level2, PR: reviewed-approved, gssoc21

#824 Updated marking scheme for GSSOC'21 in CONTRIBUTING file
  CONTRIBUTING.md
Labels: Level1, PR: unreviewed, gssoc21

#825 Fixed Word Count: split by space, newline AND tab
  src/pages/Editor/sections/OutputComponent/Output.js
Labels: Level3, PR: reviewed-approved, gssoc21

#840 Constraint on Contact number updated
  src/pages/Home/sections/Contact/components/ExperienceForm/ExperienceForm.jsx
Labels: Level2, PR: reviewed-approved, gssoc21

#839 "save as" dialog Feature before saving the file
  src/pages/Sketch/components/Canvas.js
Labels: Level2, PR: reviewed-approved, gssoc21

#848 css->scss 404 page
  src/pages/404/notFound.jsx
  src/pages/404/notFound.module.css
  src/pages/404/notFound.module.scss
  src/pages/404/squiggly-animation.scss
  src/scss/_colors.scss
Labels: Level3, PR: reviewed-approved, gssoc21

#832 css->scss: editor page
  src/index.css
  src/pages/Editor/components/DownloadFileModal/DownloadFileModal.js
  src/pages/Editor/components/DownloadFileModal/dowload-file-modal.module.scss
  src/pages/Editor/components/Slider/NumberSlider.js
  src/pages/Editor/components/Slider/Slider.module.css
  src/pages/Editor/components/Slider/slider.module.scss
  src/pages/Editor/index.js
  src/pages/Editor/sections/OutputComponent/Output.js
  src/pages/Editor/sections/OutputComponent/Output.module.css
  src/pages/Editor/sections/OutputComponent/output.module.scss
  src/pages/Editor/sections/Settings/Settings.js
  src/pages/Editor/sections/Settings/Settings.module.css
  src/pages/Editor/sections/Settings/settings.module.scss
  src/pages/Editor/style.module.scss
  src/scss/_colors.scss
Labels: Level3, gssoc21

#852 removed scrollbar from editor page
  src/pages/Editor/sections/OutputComponent/Output.js
Labels: Level2, PR: unreviewed, gssoc21

#829 added various fill options and fill modifiers
  src/pages/Sketch/Sketch.module.css
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/IconLibrary/icon-pack2/sleeping-resting-relax-bw.svg
  src/pages/Sketch/components/Toolbox/Toolbox.js
  src/pages/Sketch/components/Toolbox/toolbox.module.scss
Labels: Level3, gssoc21

#851 Animation added in Support Us!!
  src/pages/Home/sections/SupportUs/SupportUs.js
Labels: PR: unreviewed, gssoc21

#857 modified the techstack with logos
  README.md
Labels: PR: unreviewed, gssoc21

#807 Fixed: Width Bug in the Editor (Closes #798)
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.js
Labels: PR: unreviewed, deprecated

#856 Show Active Config
  src/components/Dropdown/Dropdown.js
  src/pages/Editor/sections/Settings/Settings.js
Labels: PR: unreviewed, gssoc21

#859 hovering effect added
  src/pages/Editor/sections/Settings/Settings.js
  src/pages/Editor/sections/Settings/settings.module.scss
Labels: Level2, gssoc21

#861 added media conversion & download feature @MediaManip
  package-lock.json
  package.json
  src/pages/MediaManip/DragDrop/DragDrop.jsx
  src/pages/MediaManip/MediaManip.jsx
Labels: Level3, PR: reviewed-approved, gssoc21

#855 css->scss: sketch page
  src/pages/Sketch/Sketch.js
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Canvas.module.css
  src/pages/Sketch/components/IconLibrary/IconsLibrary.jsx
  src/pages/Sketch/components/IconLibrary/icon-lib.module.css
  src/pages/Sketch/components/IconLibrary/icon-lib.module.scss
  src/pages/Sketch/components/Toolbox/Toolbox.js
  src/pages/Sketch/components/Toolbox/toolbox.module.scss
  src/pages/Sketch/components/canvas.module.scss
  src/pages/Sketch/sketch.module.scss
  src/scss/_colors.scss
Labels: PR: unreviewed, gssoc21

#875 added hovering effect and color change of hover in import
  src/pages/Editor/sections/Settings/settings.module.scss
Labels: PR: unreviewed, gssoc21

#882 [Bugfix]: #881 : Toolbox not scrolling anymore
  src/pages/Sketch/components/Toolbox/toolbox.module.scss
Labels: Level3, gssoc21

#876 Fixed bug in Media-manip page
  src/pages/MediaManip/DragDrop/DragDrop.jsx
  src/pages/MediaManip/MediaManip.jsx
Labels: Level3, PR: reviewed-approved, gssoc21

#887 toolbox modification for issue #871
  src/pages/Sketch/components/Toolbox/Toolbox.jsx
  src/pages/Sketch/components/Toolbox/toolbox.module.scss
  src/pages/Sketch/sketch.module.scss
Labels: Level3, PR: reviewed-approved, gssoc21

#894 Added no.of forks,stars,pull request,stars and license, repo size
  README.md
Labels: Level1, PR: reviewed-approved, gssoc21

#877 added hovering effect in sketch section
  src/pages/Sketch/components/canvas.module.scss
Labels: Level2, PR: reviewed-approved, gssoc21

#873 Modified Navbar
  src/components/Header/Header.module.scss
  src/components/Header/header.module.scss
Labels: gssoc21

#895 Added Moody-Regular font
  src/fonts/Moody-Regular.ttf
  src/index.scss
  src/pages/Editor/sections/Settings/Settings.jsx
Labels: Level2, gssoc21

#891 scroll-to-top of editor page
  src/App.jsx
  src/pages/Editor/Editor.jsx
  src/pages/Editor/style.module.scss
Labels: Level3, PR: reviewed-approved, gssoc21

#901 issue fixed #774 (adding import file option in sketch page)
  src/pages/Sketch/components/Canvas.jsx
Labels: Level3, PR: partially-approved, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, gssoc21

#898 delete old copies of the newly renamed files
  src/components/Header/Header.module.scss
  src/pages/404/notFound.jsx
  src/pages/Home/sections/About/About.module.scss
  src/pages/Home/sections/Banner/Banner.module.scss
  src/pages/Home/sections/Team/Team.module.scss
  src/pages/MediaManip/Button/Button.module.scss
Labels: Level3, gssoc21

#896 added Norm-Regular font
  src/fonts/Norm-Regular.ttf
  src/index.scss
  src/pages/Editor/sections/Settings/Settings.jsx
Labels: Level2, Level3, PR: reviewed-approved, gssoc21

#897 Tooltips on review emojis
  package-lock.json
  package.json
  src/pages/Home/sections/Contact/components/EmojiRating/EmojiRating.jsx
Labels: Level3, PR: reviewed-approved, gssoc21

#905 Vertical-navbar
  src/App.jsx
  src/components/Header/header.module.scss
Labels: Level3, PR: reviewed-approved, gssoc21

#906 Bug Fix: Omit output filetype options wrt input file selected
  src/pages/Editor/components/DownloadFileModal/DownloadFileModal.jsx
  src/pages/MediaManip/DragDrop/DragDrop.jsx
  src/pages/MediaManip/DropDown/DropDown.jsx
  src/pages/MediaManip/MediaManip.jsx
Labels: Level3, gssoc21

#889 new Project Maintainer UI @home
  src/assets/images/team/anush0.png
  src/assets/images/team/anush1.png
  src/assets/images/team/anush2.png
  src/assets/images/team/anush3.png
  src/assets/images/team/smaranjit0.png
  src/assets/images/team/smaranjit1.png
  src/components/Footer/Footer.jsx
  src/components/Header/header.module.scss
  src/index.scss
  src/pages/Home/Home.jsx
  src/pages/Home/sections/Team/Team.jsx
  src/pages/Home/sections/Team/components/FluidCard/FluidCard.jsx
  src/pages/Home/sections/Team/components/FluidCard/fluid-card.module.scss
  src/pages/Home/sections/Team/team.module.scss
  src/scss/_colors.scss
Labels: Level3, PR: reviewed-changes-requested, PR: unreviewed, gssoc21, merge-conflict

#911 corrected grammatical error in home page
  src/pages/Home/sections/About/About.jsx
Labels: Level0, gssoc21

#913 Added banner to readme
  README.md
  readme_assets/doc2pen.gif
Labels: PR: reviewed-approved, gssoc21

#917 Added floating animations in images of steps section
  package-lock.json
  src/pages/Home/sections/About/About.jsx
  src/pages/Home/sections/About/about.module.scss
Labels: Level3, PR: reviewed-approved, gssoc21

#919 Added Pencil Cursor for Canvas on Sketch page
  src/pages/Sketch/components/canvas.module.scss
Labels: Level2, PR: reviewed-approved, gssoc21
