Repository smaranjitghose/doc2pen, pull requests merged in 2021-03, with the labels that each got.

#566 Added logo route to home page
  package-lock.json
  src/components/Header/Header.js
Labels: PR: reviewed-approved

#573 Add Noart-Regular
  src/fonts/Noart-Regular.ttf
Labels: PR: reviewed-approved, gssoc21

#593 Corrected grammar and rephrased the README.md file
  README.md
Labels: Level-1, Level1, gssoc21

#553 textarea bug
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.js
Labels: PR: reviewed-approved, gssoc21

#603 added ctrl+z, ctrl+y shortcuts
  package-lock.json
  package.json
  src/pages/Sketch/components/Canvas.js
Labels: PR: reviewed-approved, gssoc21

#602 Removed heading in Contact page
  src/pages/Contact/ContactUs.jsx
  src/pages/Contact/ContactUs.module.css
Labels: Level2, PR: reviewed-approved, gssoc21

#609 Reformatting the Steps Layout #595
  src/pages/Home/sections/About/About.module.css
Labels: Level2, PR: reviewed-approved, gssoc21

#621 Updated CONTRIBUTING.md file
  CONTRIBUTING.md
  readme_assets/CloneRepo.png
Labels: Level0, PR: reviewed-approved, gssoc21

#618 added margin to map
  src/pages/Contact/ContactUs.module.css
Labels: Level2, PR: reviewed-approved, gssoc21

#615 Update About.module.css
  src/pages/Home/sections/About/About.module.css
Labels: Level2, PR: reviewed-approved, PR: unreviewed, gssoc21

#577 3 More Paper Friendly Font Colors are added & Contact Form's Style is improved to Align with Overall Design.
  package-lock.json
  src/components/Dropdown/Dropdown.js
  src/pages/Contact/components/ExperienceForm/ExpForm.module.css
  src/pages/Editor/sections/Settings/Settings.js
Labels: Level2, gssoc21

#604 "generating pdf toast implemented"
  package-lock.json
  package.json
  src/assets/images/editor/checkmark.svg
  src/pages/Editor/containers/editContext.js
Labels: Level3, gssoc21

#652 (Re) issue 624 resolved successfully
  src/pages/Home/sections/OpenSource/OpenSource.module.css
Labels: PR: reviewed-approved, gssoc21

#647 remove dark mode
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Canvas.module.css
  src/pages/Sketch/components/Toolbox/Toolbox.js
  src/pages/Sketch/components/Toolbox/Toolbox.module.css
Labels: PR: unreviewed, gssoc21

#653 Alerting the user if the uploaded file is not supported
  src/pages/Editor/containers/editContext.js
Labels: PR: unreviewed, gssoc21

#648 Removed blue border
  src/pages/Sketch/components/Canvas.module.css
Labels: PR: unreviewed, gssoc21

#665 UNDO/REDO feature's bug fixed
  src/pages/Sketch/components/Canvas.js
Labels: PR: unreviewed

#649 contributing.md updated
  CONTRIBUTING.md
  ContributionGuidelines.md
Labels: Level1, PR: partially-approved, PR: reviewed-approved, gssoc21

#667 [bugfix] shaking sketch UI fixed
  src/pages/Sketch/Sketch.module.css
Labels: Level2, PR: reviewed-approved, gssoc21

#675 #646 Done - Contact Us Component is Shifted to Bottom of the Home Page
  src/App.js
  src/components/Header/Header.js
  src/pages/Home/index.js
  src/pages/Home/sections/Contact/ContactUs.jsx
  src/pages/Home/sections/Contact/ContactUs.module.css
  src/pages/Home/sections/Contact/components/EmojiRating/EmojiRating.jsx
  src/pages/Home/sections/Contact/components/EmojiRating/EmojiRating.module.css
  src/pages/Home/sections/Contact/components/ExperienceForm/ExpForm.module.css
  src/pages/Home/sections/Contact/components/ExperienceForm/ExperienceForm.jsx
  src/pages/Home/sections/Contact/components/Map/Map.css
  src/pages/Home/sections/Contact/components/Map/Map.jsx
Labels: Level2, gssoc21

#689 Made all home page headings uniform
  package-lock.json
  package.json
  src/pages/Home/sections/About/About.module.css
  src/pages/Home/sections/Contact/ContactUs.jsx
  src/pages/Home/sections/Contact/ContactUs.module.css
  src/pages/Home/sections/OpenSource/OpenSource.js
  src/pages/Home/sections/OpenSource/OpenSource.module.css
  src/pages/Home/sections/SupportUs/SupportUs.js
  src/pages/Home/sections/SupportUs/SupportUs.module.css
  src/pages/Home/sections/Team/Team.js
  src/pages/Home/sections/Team/Team.module.css
Labels: Level3, PR: reviewed-approved, gssoc21

#693 Fixed padding to the editor (Issue #658)
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.js
Labels: Level2, PR: reviewed-approved, gssoc21

#704 shadow adjustment/removal + heading's top-margins @home page
  package-lock.json
  package.json
  src/pages/Home/sections/About/About.module.css
  src/pages/Home/sections/Contact/ContactUs.jsx
  src/pages/Home/sections/Contact/ContactUs.module.css
  src/pages/Home/sections/OpenSource/OpenSource.module.css
  src/pages/Home/sections/SupportUs/SupportUs.js
  src/pages/Home/sections/SupportUs/SupportUs.module.css
  src/pages/Home/sections/Team/Team.js
  src/pages/Home/sections/Team/Team.module.css
Labels: PR: unreviewed, gssoc21

#690 Add Change Background Feature @Sketch Page #634
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Toolbox/Toolbox.js
  src/pages/Sketch/components/Toolbox/Toolbox.module.css
Labels: Level3, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, gssoc21

#688 Fixed meta tag bug @ homepage
  src/pages/Home/sections/Contact/ContactUs.jsx
  src/seo/metaData.js
Labels: Level2, PR: unreviewed, gssoc21

#691 Changes to Contributors List
  src/pages/Home/sections/Team/Team.js
  src/pages/Home/sections/Team/Team.module.css
Labels: Level2, PR: partially-approved, PR: unreviewed, gssoc21

#714 Added Enola-Regular font
  src/fonts/Enola-Regular.ttf
  src/index.css
  src/pages/Editor/sections/Settings/Settings.js
Labels: PR: reviewed-approved, gssoc21

#717 text append
  package-lock.json
  package.json
  src/pages/Editor/containers/editContext.js
Labels: PR: unreviewed, gssoc21

#710 Scrollbar.
  src/pages/Home/sections/About/About.module.css
Labels: PR: unreviewed, gssoc21

#716 Added Navbar Hamburger design for smaller devices
  src/components/Header/Header.js
  src/components/Header/Header.module.css
Labels: PR: unreviewed, gssoc21

#700 icon-pack2 : stick-figures
  src/pages/Sketch/components/IconLibrary/IconsLibrary.jsx
  src/pages/Sketch/components/IconLibrary/icon-pack1/bootstrap-color.svg
  src/pages/Sketch/components/IconLibrary/icon-pack1/css-color.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.1/concentration-balance-danger-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.1/dancing-dance-elegance-balance-ballet-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.1/entertainer-mic-singer-microphone-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.1/person-balance-practicing-boy-man-activity-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.1/question-confused-sad-begging-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.1/sad-angry-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.1/sad-stick-man-cry-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.1/scratch-confused-worry-thinking-stand-head-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.1/sing-melody-music-happy-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.1/sleeping-resting-relax-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.2/running-man-1-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.2/running-man-2-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.2/running-man-3-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.2/running-man-5-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.2/tired-sad-exhausted-standing-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4/archive.svg
Labels: PR: unreviewed, gssoc21, merge-conflict

#702 icon-pack3 : speech bubbles
  src/pages/Sketch/components/IconLibrary/IconsLibrary.jsx
  src/pages/Sketch/components/IconLibrary/icon-pack2/sleeping-resting-relax-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack3/js-color.svg
  src/pages/Sketch/components/IconLibrary/icon-pack3/speech-balloon-cloud-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack3/speech-balloon-soft-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4/archive.svg
Labels: PR: unreviewed, gssoc21, merge-conflict

#723 Changing UI for sketch
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Canvas.module.css
  src/pages/Sketch/components/Toolbox/Toolbox.js
  src/pages/Sketch/components/Toolbox/Toolbox.module.css
Labels: PR: unreviewed, gssoc21

#722 Editor and Home page are now beginning at the top.
  src/pages/Editor/index.js
  src/pages/Home/index.js
Labels: PR: unreviewed, gssoc21

#724 css->scss : banner + opensource
  package-lock.json
  package.json
  src/pages/Home/sections/Banner/Banner.js
  src/pages/Home/sections/Banner/Banner.module.css
  src/pages/Home/sections/Banner/Banner.module.scss
  src/pages/Home/sections/OpenSource/OpenSource.js
  src/pages/Home/sections/OpenSource/OpenSource.module.css
  src/pages/Home/sections/OpenSource/OpenSource.module.scss
  src/scss/_colors.scss
  src/scss/_mixin.scss
Labels: PR: unreviewed, gssoc21

#703 icon-pack4 : devices and hardware icons
  package-lock.json
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/IconLibrary/IconsLibrary.jsx
  src/pages/Sketch/components/IconLibrary/icon-pack1/css-color.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.1/hiking-walking-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.1/present-smile-show-hold-stand-design-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack2.1/running-man-4-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/calculating-device-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/cpu-microchip-processor-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/devices-camera-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/devices-connected-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/devices-desktop-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/devices-headphones-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/devices-keyboard-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/devices-mouse-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/devices-watch-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/ipad-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/monitor-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/music-device-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/notebook-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/notebook-computer-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/portable-game-device-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/radio-stereo-device-retro-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/radio-with-antenna-pointing-right-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/samsung-galaxy-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/slim-device-memory-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/slim-device-memory-color.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/smartphone-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/usb-device-with-signal-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/video-record-device-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.1/vintage-television-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.2/chip-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.2/cpu-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.2/gpu-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.2/server-1-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4.2/server-2-bw.svg
  src/pages/Sketch/components/IconLibrary/icon-pack4/js-color.svg
Labels: PR: unreviewed, gssoc21, merge-conflict

#725 css->scss: About section + nav + quickbox + scrollToTop btn
  package-lock.json
  src/components/Header/Header.js
  src/components/Header/Header.module.css
  src/components/Header/Header.module.scss
  src/components/ScrollToTopButton/ScrollToTopButton.jsx
  src/components/ScrollToTopButton/scroll-to-top.module.scss
  src/components/ScrollToTopButton/style.module.css
  src/index.css
  src/pages/Home/sections/About/About.js
  src/pages/Home/sections/About/About.module.css
  src/pages/Home/sections/About/About.module.scss
  src/pages/Home/sections/OpenSource/OpenSource.module.scss
  src/scss/_colors.scss
Labels: PR: unreviewed, gssoc21

#706 Fixed scrolling issue in editor
  src/pages/Editor/sections/OutputComponent/Output.js
Labels: PR: partially-approved, gssoc21

#719 Form UI changed
  src/pages/Home/sections/Contact/ContactUs.module.css
  src/pages/Home/sections/Contact/components/EmojiRating/EmojiRating.module.css
  src/pages/Home/sections/Contact/components/ExperienceForm/ExpForm.module.css
Labels: PR: unreviewed, gssoc21

#663 Added paginatioin functionality #513
  package-lock.json
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.js
  src/pages/Editor/sections/OutputComponent/Output.module.css
  src/pages/Editor/sections/OutputComponent/Page.css
  src/pages/Editor/sections/OutputComponent/Page.js
Labels: PR: unreviewed, gssoc21, merge-conflict

#754 Revert "Added paginatioin functionality #513"
  package-lock.json
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.js
  src/pages/Editor/sections/OutputComponent/Output.module.css
  src/pages/Editor/sections/OutputComponent/Page.css
  src/pages/Editor/sections/OutputComponent/Page.js
Labels: PR: unreviewed

#738 Added New Font RayFont-Regular
  src/fonts/RayFont-Regular.ttf
  src/index.css
  src/pages/Editor/sections/Settings/Settings.js
Labels: PR: unreviewed, gssoc21

#735 Changing UI for sketch
  src/pages/Sketch/Sketch.module.css
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Toolbox/Toolbox.js
Labels: Level3, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, gssoc21

#742 added custom font RGhandwritten
  src/fonts/Rghandwritten-Regular.ttf
  src/index.css
  src/pages/Editor/sections/Settings/Settings.js
Labels: PR: unreviewed, gssoc21

#763 #758 size of hovered card fixed
  package-lock.json
  src/pages/Home/sections/OpenSource/OpenSource.module.scss
Labels: Level2, PR: reviewed-approved, gssoc21

#726 Create a New Page called MediaManip #676
  package-lock.json
  package.json
  src/App.js
  src/components/Header/Header.js
  src/index.css
  src/pages/Home/sections/OpenSource/OpenSource.module.scss
  src/pages/MediaManip/Button/Button.jsx
  src/pages/MediaManip/Button/Button.module.scss
  src/pages/MediaManip/DragDrop/DragDrop.jsx
  src/pages/MediaManip/DragDrop/DragDrop.module.scss
  src/pages/MediaManip/DropDown/DropDown.jsx
  src/pages/MediaManip/DropDown/DropDown.module.scss
  src/pages/MediaManip/MediaManip.jsx
  src/pages/MediaManip/MediaManip.module.scss
  src/pages/MediaManip/Progress/Progress.jsx
  src/pages/MediaManip/Progress/ProgressBar.module.scss
Labels: Level3, PR: reviewed-approved, gssoc21

#762 Fixes Issue #739 : Dockerized the Project
  CONTRIBUTING.md
  Dockerfile
  docker-compose.yml
Labels: Level2, PR: reviewed-approved, gssoc21

#773 added github logo and animations
  package.json
  src/assets/githublogo/github.json
  src/assets/githublogo/github.svg
  src/components/Footer/Footer.js
  src/components/Footer/footer.module.scss
  yarn.lock
Labels: PR: unreviewed, gssoc21

#782 css->scss: team section + support section
  package-lock.json
  package.json
  src/pages/Home/sections/SupportUs/SupportUs.js
  src/pages/Home/sections/SupportUs/SupportUs.module.css
  src/pages/Home/sections/SupportUs/SupportUs.module.scss
  src/pages/Home/sections/Team/Team.js
  src/pages/Home/sections/Team/Team.module.css
  src/pages/Home/sections/Team/Team.module.scss
  src/scss/_colors.scss
Labels: Level2, PR: reviewed-approved, gssoc21

#784 bugfix: Editor editcontext is not switching
  src/pages/Editor/sections/OutputComponent/Output.js
  src/pages/Editor/sections/Settings/Settings.js
Labels: Level2, PR: unreviewed, gssoc21

#788 Canvas background Color Bug fixed
  src/pages/Sketch/components/Canvas.js
Labels: Level3, PR: reviewed-approved, gssoc21

#790 opacity setting UI
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Canvas.module.css
  src/pages/Sketch/components/Toolbox/Toolbox.js
  src/pages/Sketch/components/Toolbox/Toolbox.module.css
  src/pages/Sketch/components/Toolbox/toolbox.module.scss
Labels: Level2, PR: reviewed-approved, gssoc21

#785 Remove toTop button for smaller screens (when screen-width < 768px)
  src/pages/Home/home.module.scss
  src/pages/Home/index.js
Labels: Level2, PR: reviewed-approved, gssoc21

#786 removed quote section@Home
  package-lock.json
  src/pages/Home/sections/OpenSource/OpenSource.js
  src/pages/Home/sections/OpenSource/OpenSource.module.scss
  src/pages/Home/sections/SupportUs/SupportUs.js
  src/pages/Home/sections/SupportUs/SupportUs.module.scss
Labels: Level2, gssoc21

#795 [bugfix] Contributor_Section Bug @Home Page
  src/pages/Home/sections/Team/Team.module.scss
Labels: Level2, PR: reviewed-approved, gssoc21

#796 [bugfix] Spacing Bug Mobile View @Home Page
  src/pages/Home/sections/About/About.module.scss
  src/pages/Home/sections/Contact/contact-us.module.scss
Labels: Level2, PR: reviewed-approved, gssoc21

#794 Added Cedarville Cursive Font to the Editor
  src/pages/Editor/sections/Settings/Settings.js
Labels: Level2, gssoc21

#799 add stroke+fill color
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Toolbox/Toolbox.js
Labels: Level3, PR: reviewed-approved, PR: unreviewed, gssoc21

#791 canvas rough pen style
  package-lock.json
  package.json
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Toolbox/Toolbox.js
  src/pages/Sketch/components/Toolbox/toolbox.module.scss
Labels: Level3, gssoc21

#781 Custom File name Feature
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/Settings/DownloadFileModal.js
  src/pages/Editor/sections/Settings/Settings.js
  src/pages/Editor/sections/Settings/Settings.module.css
Labels: Level3, gssoc21

#806 Fix: Added Scrollbar on all pages
  src/pages/Editor/sections/OutputComponent/Output.module.css
Labels: Level2, PR: reviewed-approved, gssoc21

#753 Add Bi Shape Triangle
  package-lock.json
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Toolbox/Toolbox.js
Labels: PR: unreviewed, gssoc21

#816 enhancement- pen draws on the fly!!
  src/pages/Sketch/components/Canvas.js
Labels: Level3, PR: reviewed-approved, gssoc21

#817 rough shapes implemented
  src/pages/Sketch/components/Canvas.js
Labels: Level3, gssoc21

#814 persistent canvas state (localstorage)
  src/pages/Sketch/components/Canvas.js
Labels: Level3, PR: reviewed-approved, gssoc21

#797 Removed Head Body Distinction in Editor
  src/components/Dropdown/Dropdown.js
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.js
  src/pages/Editor/sections/OutputComponent/Output.module.css
  src/pages/Editor/sections/Settings/Settings.js
  src/pages/Editor/sections/Settings/Settings.module.css
Labels: PR: reviewed-approved, gssoc21
