Repository smaranjitghose/doc2pen, pull requests merged in 2021-02, with the labels that each got.

#435 REACT: Text Overflow Of Cards
  src/pages/Home/sections/OpenSource/OpenSource.module.css
Labels: DWOC, Level-3

#437 Update Team Section (Fixes #433)
  src/pages/Home/sections/Team/Team.js
Labels: DWOC, Easy, PR: reviewed-approved

#441 Fixes #434 (Card Images)
  src/pages/Home/sections/Team/Team.js
Labels: DWOC, Level-3, PR: reviewed-approved

#444 Uniform NavBar and Quick Links (Fixes #438)
  src/components/Header/Header.js
  src/components/Header/Header.module.css
Labels: DWOC, Level-5

#450 responsiveness feature for home page
  src/components/Footer/Footer.css
  src/components/Header/Header.module.css
  src/pages/Home/index.js
  src/pages/Home/sections/About/About.js
  src/pages/Home/sections/About/About.module.css
  src/pages/Home/sections/Banner/Banner.js
  src/pages/Home/sections/Banner/Banner.module.css
  src/pages/Home/sections/ContactUs/ContactUs.js
  src/pages/Home/sections/ContactUs/ContactUs.module.css
  src/pages/Home/sections/OpenSource/OpenSource.module.css
  src/pages/Home/sections/SupportUs/SupportUs.js
  src/pages/Home/sections/SupportUs/SupportUs.module.css
  src/pages/Home/sections/Team/Team.module.css
Labels: DWOC, Hard, Level-5, PR: reviewed-approved, SWoC2021

#449 REACT:Import Text From Doc or txt file� #402
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.js
  src/pages/Editor/sections/Settings/Settings.js
Labels: Hard, PR: reviewed-approved, SWoC2021, enhancement

#448 fixes #445. change x-axis
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/Settings/Settings.js
Labels: DWOC, Easy, Level-3, PR: reviewed-approved, SWoC2021

#442 Make button functional and also align.
  src/pages/Home/sections/Banner/Banner.js
  src/pages/Home/sections/Banner/Banner.module.css
Labels: Easy, PR: reviewed-approved, PR: unreviewed, SWoC2021

#447 width and linespacing: done. Extra feature😁😁: Letterspacing
  src/pages/Editor/components/Slider/NumberSlider.js
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.js
  src/pages/Editor/sections/Settings/Settings.js
Labels: DWOC, Level-4, Medium, SWoC2021

#457 [fix]: netlify routing problem
  public/_redirects
Labels: DWOC, Easy, Level-3, PR: reviewed-approved, SWoC2021

#456 rescaled x-axis adjustment
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.js
  src/pages/Editor/sections/Settings/Settings.js
Labels: DWOC, Easy, Level-4, PR: reviewed-approved, SWoC2021

#459 Sketch: Pen Color and Width
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Canvas.module.css
  src/pages/Sketch/components/Toolbox/Toolbox.js
  src/pages/Sketch/components/Toolbox/Toolbox.module.css
Labels: DWOC, Level-4, PR: reviewed-approved

#469 Top Home Section Responsive
  src/components/Header/Header.js
  src/components/Header/Header.module.css
  src/pages/Home/sections/Banner/Banner.module.css
Labels: DWOC, Level-4, Medium, PR: reviewed-approved, SWoC2021

#472 SEO (react-helmet)
  package-lock.json
  package.json
  public/index.html
  src/pages/Editor/index.js
  src/pages/Home/index.js
  src/pages/Sketch/Sketch.js
  src/seo/MetaComponent.js
  src/seo/metaData.js
Labels: DWOC, Hard, Level-5, PR: reviewed-approved, SWoC2021

#473 alignment fixed
  src/components/Header/Header.js
  src/components/Header/Header.module.css
Labels: DWOC, Easy, Level-3, PR: reviewed-approved, SWoC2021

#468 REACT:Added interactive feedback section in contact us form and improve code for the same.
  src/pages/Home/sections/ContactUs/ContactUs.js
  src/pages/Home/sections/ContactUs/ContactUs.module.css
Labels: DWOC, Easy, Level-3, SWoC2021, user=Abhijay007:score=25

#477 converted all css to css modules
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.module.css
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Footer/Footer.module.css
  src/components/ScrollToTopButton/ScrollToTopButton.jsx
  src/components/ScrollToTopButton/style.module.css
  src/index.css
  src/pages/Editor/components/Slider/NumberSlider.js
  src/pages/Editor/components/Slider/Slider.module.css
  src/pages/Editor/index.js
  src/pages/Editor/sections/Settings/Settings.js
  src/pages/Editor/sections/Settings/Settings.module.css
  src/pages/Editor/style.module.css
Labels: DWOC, Easy, Level-3, MWOC, PR: reviewed-approved, SWoC2021, user=ashuvssut:score=25

#487 Sketch Shapes Draw Feature
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Canvas.module.css
Labels: DWOC, Hard, Level-5, MWOC, PR: reviewed-approved, SWoC2021, user=sanjay270899:score=100

#479 [feature: improved performance] image sizes resized, srcset applied
  assets/js/main.js
  public/images/events/SLOP.png
  public/images/events/SWOC-logo.png
  public/images/events/hakin_codes.png
  public/images/events/psoc_logo.png
  public/images/events/woc-logo.png
  src/assests/images/team/anush_bhatia_large.png
  src/assests/images/team/anush_bhatia_small.png
  src/assests/images/team/smaranjit_ghose_large.png
  src/assests/images/team/smaranjit_ghose_small.png
  src/components/Header/logo.png
  src/pages/Home/sections/Team/Team.js
  src/pages/Home/sections/Team/Team.module.css
Labels: DWOC, Level-4, MWOC, Medium, PR: partially-approved, SWoC2021, user=ashuvssut:score=50

#482 sketch button width fix
  src/components/Header/Header.module.css
Labels: DWOC, Easy, Level-3, MWOC, PR: reviewed-approved, SWoC2021, user=ashuvssut:score=25

#481 [feature: performance] added cache control
  netlify.toml
Labels: PR: unreviewed

#490 minor changes
  src/assets/images/team/anush_bhatia.png
  src/assets/images/team/anush_bhatia_large.png
  src/assets/images/team/anush_bhatia_small.png
  src/assets/images/team/smaranjit_ghose.png
  src/assets/images/team/smaranjit_ghose_large.png
  src/assets/images/team/smaranjit_ghose_small.png
  src/components/Header/Header.js
  src/pages/Home/sections/Team/Team.js
  src/pages/Home/sections/Team/Team.module.css
Labels: Beginner, DWOC, Level-2, PR: reviewed-approved, SWoC2021

#485 Hamburger button now works as desired
  src/components/Header/Header.js
  src/components/Header/Header.module.css
Labels: DWOC, Easy, Level-3, MWOC, SWoC2021, user=ashuvssut:score=25

#500 Sketch: Fill, Opacity, and Stroke
  src/pages/Sketch/Sketch.js
  src/pages/Sketch/Sketch.module.css
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Canvas.module.css
  src/pages/Sketch/components/Toolbox/Toolbox.js
  src/pages/Sketch/components/Toolbox/Toolbox.module.css
Labels: CrossWOC, DWOC, Hard, Level-5, MWOC, PR: reviewed-approved, SWoC2021, user=sanjay270899:score=100

#505 update caching policy
  netlify.toml
Labels: CrossWOC, Easy, Level-3, MWOC, PR: reviewed-approved, SWoC2021, user=ashuvssut:score=25

#504 [performance] added preconnect tag to establish early connection to api.github.com
  public/index.html
Labels: CrossWOC, DWOC, Easy, Level-3, MWOC, PR: reviewed-approved, SWoC2021, user=ashuvssut:score=25

#507 Readme open src upd
  README.md
  assets/.DS_Store
  assets/images/d2p.png
  assets/images/doc2penlogo.png
  assets/js/main.js
  public/images/events/SWOC-logo.webp
  public/images/team/anush_bhatia.png
  public/images/team/smaranjit_ghose.png
  readme_assets/SLOP.webp
  readme_assets/SWOC-logo.webp
  src/assets/images/events/SLOP.webp
  src/assets/images/events/SWOC-logo.webp
  src/assets/images/events/crosswoc.webp
  src/assets/images/events/gssoc.webp
  src/assets/images/events/hakin_codes.webp
  src/assets/images/events/jwoc.webp
  src/assets/images/events/mwoc.webp
  src/assets/images/events/psoc_logo.webp
  src/assets/images/events/woc-logo.webp
  src/assets/images/home-about/open-source.svg
  src/assets/images/home-about/step1.svg
  src/assets/images/home-about/step2.svg
  src/assets/images/home-about/step3.svg
  src/assets/images/home-about/step4.svg
  src/assets/images/home-banner/pen.svg
  src/assets/images/home-banner/wave.png
  src/assets/logo/logo.png
  src/assets/logo/logo.webp
  src/components/Header/Header.js
  src/logo.svg
  src/pages/Home/sections/About/About.js
  src/pages/Home/sections/Banner/Banner.js
  src/pages/Home/sections/Banner/Banner.module.css
  src/pages/Home/sections/OpenSource/OpenSource.js
Labels: Beginner, CrossWOC, DWOC, Level-2, PR: reviewed-approved, SWoC2021, user=ashuvssut:score=25

#525 ✨ Revamp Sketch Layout
  src/pages/Editor/style.module.css
  src/pages/Sketch/Sketch.js
  src/pages/Sketch/Sketch.module.css
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Canvas.module.css
  src/pages/Sketch/components/Toolbox/Toolbox.js
  src/pages/Sketch/components/Toolbox/Toolbox.module.css
Labels: CrossWOC, DWOC, Hard, Level-5, MWOC, PR: reviewed-approved, SWoC2021, user=sanjay270899:score=100

#470 404 page done
  public/index.html
  src/App.js
  src/assets/images/404/404-bg.svg
  src/assets/images/404/Fade-In-Background.svg
  src/assets/images/404/Logo.png
  src/assets/images/404/Logo1.png
  src/assets/images/404/Logo2.png
  src/assets/images/404/Logo3.png
  src/assets/images/404/Motion-Background.svg
  src/assets/images/404/Shadow-Fall-Background.svg
  src/assets/images/404/bubble-animated-background.svg
  src/components/Preloader/Preloader.jsx
  src/index.js
  src/pages/404/notFound.jsx
  src/pages/404/notFound.module.css
  src/pages/404/particles.css
Labels: DWOC, Level-4, MWOC, Medium, PR: partially-approved, SWoC2021, user=ashuvssut:score=50

#520 create web_optimization.md
  WEB_OPTIMIZATION.md
Labels: Beginner, DWOC, Level-2, MWOC, PR: reviewed-approved, SWoC2021, user=ashuvssut:score=25

#537 [bugfix]: When clicked on decrement button of any settings on editor page-- Error appears
  src/pages/Editor/components/Slider/NumberSlider.js
Labels: PR: unreviewed

#538 [feature]: Select on text areas to toggle settings mode ( body or title)
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.js
  src/pages/Editor/sections/Settings/Settings.js
Labels: DWOC, Level-4, MWOC, Medium, PR: reviewed-approved, SWoC2021, user=ashuvssut:score=50

#522 Contribution Guidelines Markdown
  ContributionGuidelines.md
  readme_assets/Cloning Project (1).png
  readme_assets/Fork Project.png
  readme_assets/PR.JPG
Labels: CrossWOC, DWOC, Easy, Level-3, SWoC2021

#539 Sketch: Undo and Redo
  src/pages/Sketch/Sketch.module.css
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Toolbox/Toolbox.js
  src/pages/Sketch/components/Toolbox/Toolbox.module.css
Labels: DWOC, Level-5, MWOC, Medium, PR: reviewed-approved, SWoC2021, user=sanjay270899:score=100

#541 Eraser added
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Toolbox/Toolbox.js
Labels: PR: unreviewed

#542 Dynamic favicon
  public/404browser_102160.png
  public/doc2penlogo.png
  public/faviconn.ico
  public/index.html
  src/App.js
  src/pages/404/notFound.jsx
Labels: PR: reviewed-approved

#552 Revert "Eraser added"
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Toolbox/Toolbox.js
Labels: PR: unreviewed

#534 revamped contact-us section
  package-lock.json
  package.json
  public/index.html
  src/pages/Home/components/EmojiRating/EmojiRating.jsx
  src/pages/Home/components/EmojiRating/EmojiRating.module.css
  src/pages/Home/components/ExperienceForm/ExpForm.module.css
  src/pages/Home/components/ExperienceForm/ExperienceForm.jsx
  src/pages/Home/components/Map/Map.css
  src/pages/Home/components/Map/Map.jsx
  src/pages/Home/index.js
  src/pages/Home/sections/ContactUs/ContactUs.js
  src/pages/Home/sections/ContactUs/ContactUs.module.css
Labels: DWOC, Hard, Level-5, MWOC, PR: reviewed-changes-requested, PR: unreviewed, SWoC2021, user=ashuvssut:score=100

#545 Fixed type error caused by scroll to top button #543
  src/components/ScrollToTopButton/ScrollToTopButton.jsx
Labels: PR: reviewed-approved

#555 [feature] dynamic title
  public/folded.png
  src/seo/MetaComponent.js
Labels: DWOC, Level-4, MWOC, Medium, SWoC2021, user=ashuvssut:score=50

#532 [feature]: pdf download feature added
  package-lock.json
  package.json
  src/components/Dropdown/Dropdown.js
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/Settings/Settings.js
Labels: DWOC, Hard, Level-5, MWOC, SWoC2021, user=ashuvssut:score=100

#550 Sketch Dark Mode
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Canvas.module.css
  src/pages/Sketch/components/Toolbox/Toolbox.js
  src/pages/Sketch/components/Toolbox/Toolbox.module.css
Labels: DWOC, Hard, Level-5, MWOC, SWoC2021, user=sanjay270899:score=100

#554 [feature] New contact page
  src/App.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.module.css
  src/components/Header/Header.js
  src/pages/Contact/ContactUs.jsx
  src/pages/Contact/ContactUs.module.css
  src/pages/Contact/components/EmojiRating/EmojiRating.jsx
  src/pages/Contact/components/EmojiRating/EmojiRating.module.css
  src/pages/Contact/components/ExperienceForm/ExpForm.module.css
  src/pages/Contact/components/ExperienceForm/ExperienceForm.jsx
  src/pages/Contact/components/Map/Map.css
  src/pages/Contact/components/Map/Map.jsx
  src/pages/Editor/index.js
  src/pages/Home/components/ExperienceForm/ExperienceForm.jsx
  src/pages/Home/components/Map/Map.css
  src/pages/Home/components/Map/Map.jsx
  src/pages/Home/index.js
  src/seo/metaData.js
Labels: DWOC, Hard, Level-5, MWOC, SWoC2021, user=ashuvssut:score=100

#557 Sketch: Text Feature
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Canvas.module.css
  src/pages/Sketch/components/Toolbox/Toolbox.js
Labels: DWOC, Level-4, MWOC, Medium, PR: reviewed-approved, SWoC2021, user=sanjay270899:score=50

#559 Sketch: Fill Pattern
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Toolbox/Toolbox.js
Labels: Hard, MWOC, PR: reviewed-approved, SWoC2021, user=sanjay270899:score=100

#558 Sketch: Label on Hover
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Canvas.module.css
  src/pages/Sketch/components/Toolbox/Toolbox.js
Labels: Hard, MWOC, PR: reviewed-approved, SWoC2021, user=sanjay270899:score=100

#561 Sketch: Improvements and Edge Feature
  src/App.js
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Toolbox/Toolbox.js
  src/pages/Sketch/components/Toolbox/Toolbox.module.css
Labels: Hard, MWOC, SWoC2021, user=sanjay270899:score=100

#549 404 UI
  src/assets/images/404/Logo-blue-thick-x.png
  src/assets/images/404/Logo-blue-thin-x.png
  src/assets/images/404/Logo-blue.png
  src/assets/images/404/Logo-darkblue.png
  src/assets/images/404/Logo-red.png
  src/assets/images/404/Logo-white.png
  src/assets/images/404/LogoMakr-0OzLs9.png
  src/assets/images/404/astro.svg
  src/assets/images/404/astroman.png
  src/assets/images/404/sad404.svg
  src/assets/images/404/skate.svg
  src/assets/images/404/skate2.svg
  src/fonts/LuckiestGuy-Regular.ttf
  src/index.css
  src/pages/404/notFound.jsx
  src/pages/404/notFound.module.css
  src/pages/404/particles.css
  src/pages/404/squiggly-animation.css
  src/seo/metaData.js
Labels: DWOC, Hard, Level-4, MWOC, SWoC2021, user=ashuvssut:score=100
