Repository smaranjitghose/doc2pen, pull requests merged in 2021-05, with the labels that each got.

#922 fix bugs in sketch page "save d2ps feature" and "load images feature"
  src/pages/Sketch/components/Canvas.jsx
Labels: PR: unreviewed, gssoc21

#925 Fix bug : cannot read property "offsetWidth' of null
  src/App.jsx
  src/components/Header/Header.jsx
  src/pages/Home/sections/Team/components/FluidCard/FluidCard.jsx
Labels: PR: unreviewed, gssoc21

#923 Sidebar update in Sketch page
  package-lock.json
  package.json
  src/App.jsx
  src/assets/images/sketch/d2ps.svg
  src/pages/Sketch/components/Canvas.jsx
  src/pages/Sketch/components/IconLibrary/IconsLibrary.jsx
  src/pages/Sketch/components/IconLibrary/icon-lib.module.scss
  src/pages/Sketch/components/Toolbox/Toolbox.jsx
  src/pages/Sketch/components/Toolbox/toolbox.module.scss
Labels: Level3, PR: reviewed-approved, gssoc21

#935 [bugfix]: THE icons in icons library do not load unless we hover our mouse on canvas area
  public/index.html
  src/pages/Sketch/components/IconLibrary/IconsLibrary.jsx
Labels: Level3, gssoc21

#927 restyle the Editor toolbox to restore the old missing style
  src/components/Dropdown/dropdown.module.scss
  src/pages/Editor/components/Slider/NumberSlider.jsx
  src/pages/Editor/components/Slider/slider.module.scss
  src/pages/Editor/sections/Settings/Settings.jsx
  src/pages/Editor/sections/Settings/settings.module.scss
  src/pages/MediaManip/DropDown/DropDown.jsx
Labels: Level3, gssoc21

#941 Clean the code
  src/App.jsx
  src/index.js
  src/index.scss
  src/pages/404/not-found.module.scss
  src/pages/Editor/components/DownloadFileModal/DownloadFileModal.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/sections/Banner/banner.module.scss
  src/pages/MediaManip/Button/Button.jsx
  src/pages/MediaManip/DragDrop/DragDrop.jsx
  src/pages/MediaManip/DropDown/DropDown.jsx
  src/pages/MediaManip/DropDown/drop-down.module.scss
  src/pages/Sketch/components/Canvas.jsx
  src/pages/Sketch/components/IconLibrary/IconsLibrary.jsx
  src/pages/Sketch/components/Toolbox/Toolbox.jsx
  src/scss/_colors.scss
  src/seo/MetaComponent.jsx
  src/seo/metaData.js
Labels: Level3, gssoc21

#940 Added option for Bold Text in Editor
  src/components/Dropdown/Dropdown.jsx
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.jsx
  src/pages/Editor/sections/Settings/Settings.jsx
Labels: Level3, PR: reviewed-approved, gssoc21

#948 Added media queries for mobile devices
  src/pages/Home/sections/About/about.module.scss
Labels: Level3, gssoc21

#946 Hide Dropdown on changing Route / Page on Mobile
  src/components/Header/Header.jsx
Labels: Level3, PR: reviewed-approved, gssoc21

#950 Updated Button
  src/pages/Home/sections/OpenSource/open-source.module.scss
Labels: Level3, PR: reviewed-approved, gssoc21

#951 Increased the contacts icons size
  src/components/Header/Header.jsx
  src/components/Header/header.module.scss
Labels: PR: reviewed-approved, gssoc21

#957 Implemented add/remove page buttons, also added page number display
  src/pages/Editor/Editor.jsx
  src/pages/Editor/sections/OutputComponent/Output.jsx
  src/pages/Editor/style.module.scss
Labels: Level3, PR: reviewed-approved, gssoc21

#956 Made Text in Textareas Visible on Selection
  src/index.scss
Labels: Level3, PR: reviewed-approved, gssoc21

#971 Updated Pitch to include all functionalities
  src/pages/Home/sections/About/About.jsx
Labels: Level3, PR: reviewed-approved, gssoc21

#973 Updated the Pitch / Opening Section of ReadMe
  README.md
Labels: Level2, PR: reviewed-approved, gssoc21

#976 Updated Steps section (both text and images) for Homepage
  src/assets/images/home-about/step1.svg
  src/assets/images/home-about/step2.svg
  src/assets/images/home-about/step3.svg
  src/assets/images/home-about/step4.svg
  src/pages/Home/sections/About/About.jsx
Labels: Level3, PR: reviewed-approved, gssoc21

#982 Fixed Multiple Files Conversion Bug
  src/pages/MediaManip/MediaManip.jsx
Labels: Level3, PR: reviewed-approved, gssoc21

#984 Implemented Buttons to Toggle between Pages
  src/pages/Editor/Editor.jsx
  src/pages/Editor/sections/OutputComponent/Output.jsx
Labels: Level3, PR: unreviewed, gssoc21

#987 Fixed Multiple Page Exports Bug (Both PNG and PDF format)
  src/pages/Editor/components/DownloadFileModal/DownloadFileModal.jsx
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.jsx
Labels: Level3, PR: reviewed-approved, gssoc21

#985 Made it possible for user to drag and drop files multiple times
  src/pages/MediaManip/DragDrop/DragDrop.jsx
  src/pages/MediaManip/DragDrop/drag-drop.module.scss
  src/pages/MediaManip/MediaManip.jsx
Labels: PR: unreviewed, gssoc21

#993 Made Media Manip Page Responsive
  src/pages/MediaManip/DragDrop/drag-drop.module.scss
  src/pages/MediaManip/DropDown/drop-down.module.scss
  src/pages/MediaManip/media-manip.module.scss
Labels: Level3, PR: reviewed-approved, gssoc21

#990 Multiple PNG pages are now Exported as 1 Zipped folder
  src/pages/Editor/containers/editContext.js
Labels: Level3, PR: reviewed-approved, gssoc21

#992 eslint config added and errors corrected
  .eslintrc.js
  package-lock.json
  package.json
  src/App.jsx
  src/App.test.js
  src/components/Dropdown/Dropdown.jsx
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/Preloader/Preloader.jsx
  src/components/ScrollToTopButton/ScrollToTopButton.jsx
  src/index.js
  src/pages/404/NotFound.jsx
  src/pages/Editor/Editor.jsx
  src/pages/Editor/components/DownloadFileModal/DownloadFileModal.jsx
  src/pages/Editor/components/Slider/NumberSlider.jsx
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.jsx
  src/pages/Editor/sections/Settings/Settings.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/sections/About/About.jsx
  src/pages/Home/sections/Banner/Banner.jsx
  src/pages/Home/sections/Contact/ContactUs.jsx
  src/pages/Home/sections/Contact/components/EmojiRating/EmojiRating.jsx
  src/pages/Home/sections/Contact/components/ExperienceForm/ExperienceForm.jsx
  src/pages/Home/sections/Contact/components/Map/Map.jsx
  src/pages/Home/sections/OpenSource/OpenSource.jsx
  src/pages/Home/sections/SupportUs/SupportUs.jsx
  src/pages/Home/sections/Team/Team.jsx
  src/pages/Home/sections/Team/components/FluidCard/FluidCard.jsx
  src/pages/MediaManip/Button/Button.jsx
  src/pages/MediaManip/DragDrop/DragDrop.jsx
  src/pages/MediaManip/DropDown/DropDown.jsx
  src/pages/MediaManip/MediaManip.jsx
  src/pages/MediaManip/Progress/Progress.jsx
  src/pages/Sketch/Sketch.jsx
  src/pages/Sketch/components/Canvas.jsx
  src/pages/Sketch/components/IconLibrary/IconsLibrary.jsx
  src/pages/Sketch/components/Toolbox/Toolbox.jsx
  src/reportWebVitals.js
  src/seo/MetaComponent.jsx
  src/seo/metaData.js
  yarn.lock
Labels: PR: unreviewed, gssoc21, merge-conflict

#999 Resolve eslint errors
  src/components/Dropdown/Dropdown.jsx
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/ScrollToTopButton/ScrollToTopButton.jsx
  src/pages/404/NotFound.jsx
  src/pages/Editor/Editor.jsx
  src/pages/Editor/components/DownloadFileModal/DownloadFileModal.jsx
  src/pages/Editor/components/Slider/NumberSlider.jsx
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.jsx
  src/pages/Editor/sections/Settings/Settings.jsx
  src/pages/Home/sections/About/About.jsx
  src/pages/Home/sections/Banner/Banner.jsx
  src/pages/Home/sections/Contact/ContactUs.jsx
  src/pages/Home/sections/Contact/components/EmojiRating/EmojiRating.jsx
  src/pages/Home/sections/Contact/components/ExperienceForm/ExperienceForm.jsx
  src/pages/Home/sections/Contact/components/Map/Map.jsx
  src/pages/Home/sections/OpenSource/OpenSource.jsx
  src/pages/Home/sections/SupportUs/SupportUs.jsx
  src/pages/Home/sections/Team/Team.jsx
  src/pages/Home/sections/Team/components/FluidCard/FluidCard.jsx
  src/pages/MediaManip/Button/Button.jsx
  src/pages/MediaManip/DragDrop/DragDrop.jsx
  src/pages/MediaManip/MediaManip.jsx
  src/pages/Sketch/components/Canvas.jsx
  src/pages/Sketch/components/IconLibrary/IconsLibrary.jsx
  src/pages/Sketch/components/Toolbox/Toolbox.jsx
  src/seo/metaData.js
Labels: PR: unreviewed, gssoc21

#995 Added Feature to Convert any Number of Images to 1 Pdf file
  .eslintrc.js
  src/pages/Editor/containers/editContext.js
  src/pages/MediaManip/MediaManip.jsx
Labels: PR: unreviewed, gssoc21, merge-conflict

#1011 Experience Form Validation + Regex + other Input tag attributes
  src/pages/Home/sections/Contact/components/EmojiRating/EmojiRating.jsx
  src/pages/Home/sections/Contact/components/ExperienceForm/ExperienceForm.jsx
Labels: Level3, PR: reviewed-approved, gssoc21

#1013 Added Feature to Directly Navigate to any Page by it's Number on Editor Page
  src/pages/Editor/Editor.jsx
Labels: Level3, PR: reviewed-approved, gssoc21

#1009 Fixes #994
  src/pages/Home/sections/About/About.jsx
Labels: Level1, PR: reviewed-approved, gssoc21

#1003 Resolve All DevTools Console Warnings (All pages)
  package-lock.json
  package.json
  src/components/Dropdown/Dropdown.jsx
  src/pages/Editor/sections/OutputComponent/Output.jsx
  src/pages/Home/sections/Contact/components/ExperienceForm/ExperienceForm.jsx
  src/pages/Sketch/components/IconLibrary/IconsLibrary.jsx
  src/pages/Sketch/components/Toolbox/Toolbox.jsx
  yarn.lock
Labels: Level3, PR: reviewed-approved, gssoc21

#1007 Restore eslint rules + resolve errors that show up from dev server
  .eslintrc.js
  src/pages/Editor/containers/editContext.js
  src/pages/MediaManip/MediaManip.jsx
Labels: Level3, PR: reviewed-approved, gssoc21

#1018 add prettier action
  .github/workflows/prettier_action_on_PR_and_push.yml
Labels: PR: unreviewed, gssoc21

#996 new preloader
  src/components/Preloader/Preloader.jsx
  src/components/Preloader/preloader.module.scss
Labels: Level3, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, gssoc21, merge-conflict

#1005 Fixed Image to PDF conversion, Resolution and Dimensions preserved
  src/pages/MediaManip/MediaManip.jsx
Labels: Level3, PR: reviewed-approved, PR: unreviewed, gssoc21

#1024 add dependabot
  .github/dependabot.yml
Labels: PR: unreviewed, gssoc21

#1021 Add Linters config files
  .eslintrc.js
  .prettierignore
  .prettierrc.js
Labels: Level3, gssoc21

#1022 resolve eslint errors that came through commit 22c0840
  src/App.jsx
  src/components/Dropdown/Dropdown.jsx
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/Preloader/Preloader.jsx
  src/components/ScrollToTopButton/ScrollToTopButton.jsx
  src/index.js
  src/pages/404/NotFound.jsx
  src/pages/Editor/Editor.jsx
  src/pages/Editor/components/DownloadFileModal/DownloadFileModal.jsx
  src/pages/Editor/components/Slider/NumberSlider.jsx
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.jsx
  src/pages/Editor/sections/Settings/Settings.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/sections/About/About.jsx
  src/pages/Home/sections/Banner/Banner.jsx
  src/pages/Home/sections/Contact/ContactUs.jsx
  src/pages/Home/sections/Contact/components/EmojiRating/EmojiRating.jsx
  src/pages/Home/sections/Contact/components/ExperienceForm/ExperienceForm.jsx
  src/pages/Home/sections/Contact/components/Map/Map.jsx
  src/pages/Home/sections/OpenSource/OpenSource.jsx
  src/pages/Home/sections/SupportUs/SupportUs.jsx
  src/pages/Home/sections/Team/Team.jsx
  src/pages/Home/sections/Team/components/FluidCard/FluidCard.jsx
  src/pages/MediaManip/Button/Button.jsx
  src/pages/MediaManip/DragDrop/DragDrop.jsx
  src/pages/MediaManip/DropDown/DropDown.jsx
  src/pages/MediaManip/MediaManip.jsx
  src/pages/MediaManip/Progress/Progress.jsx
  src/pages/Sketch/Sketch.jsx
  src/pages/Sketch/components/Canvas.jsx
  src/pages/Sketch/components/IconLibrary/IconsLibrary.jsx
  src/pages/Sketch/components/Toolbox/Toolbox.jsx
  src/reportWebVitals.js
  src/seo/MetaComponent.jsx
  src/seo/metaData.js
Labels: Level3, gssoc21

#1033 performance improvements
  .prettierrc.js
  src/App.jsx
Labels: Level2, PR: reviewed-approved, gssoc21

#1032 Updated Page Heading to File Converter
  src/pages/MediaManip/MediaManip.jsx
Labels: Level1, PR: reviewed-approved, PR: unreviewed, gssoc21

#1030 Added Feature to Merge any Number of PDFs into 1
  package-lock.json
  package.json
  src/pages/MediaManip/DragDrop/DragDrop.jsx
  src/pages/MediaManip/MediaManip.jsx
Labels: Level3, PR: reviewed-approved, gssoc21

#1028 Fixed page Responsiveness issue
  .prettierrc.js
  src/index.scss
  src/pages/Home/sections/Banner/banner.module.scss
  src/pages/Home/sections/OpenSource/open-source.module.scss
  src/pages/Home/sections/Team/Team.jsx
  src/pages/Home/sections/Team/team.module.scss
  src/scss/_mixin.scss
Labels: Level3, PR: reviewed-approved, gssoc21
