Repository smaranjitghose/doc2pen, pull requests merged in 2021-01, with the labels that each got.

#327 added border and fix merge conflict
  assets/.DS_Store
  assets/images/pages/page (10).jpg
  assets/images/pages/page (11).jpg
  assets/images/pages/page (12).jpg
  assets/images/pages/page (13).jpg
  assets/images/pages/page (8).jpg
  assets/images/pages/page (9).jpg
  assets/js/editor.js
  editor.html
Labels: DWOC, Level-4

#326 Updated readme
  .github/contribution.md
  README.md
  assets/Readme_assets/dwoc.png
  assets/Readme_assets/hacktoberfest.png
Labels: DWOC, Level-3

#328 updated the hover effect #299
  assets/css/style.css
Labels: DWOC, Level-3

#336 [added feature]: added sliders on the edges of the output canvas
  assets/css/editor.css
  assets/css/style.css
  assets/js/editor.js
  editor.html
Labels: PR: unreviewed

#341 solved map overlapping problem
  assets/css/style.css
Labels: PR: reviewed-approved

#349 Fixed Responsive Navbar #342
  assets/css/style.css
  assets/js/main.js
Labels: Medium, SWoC2021

#346 Added Import from .txt Option
  editor.html
Labels: Medium, SWoC2021

#347 Added Import from .doc Option
  editor.html
Labels: Medium, SWoC2021

#361 Canvas color
  assets/css/painter.css
  assets/js/painter.js
  painter.html
Labels: Medium, SWoC2021

#362 added the new logo
  assets/images/d2p.png
  assets/images/doc2penlogo.png
  assets/images/logo-new.png
  assets/js/main.js
Labels: Medium, SWoC2021

#373 Revert "added the new logo"
  assets/images/d2p.png
  assets/images/doc2penlogo.png
  assets/images/logo-new.png
  assets/js/main.js
Labels: PR: unreviewed

#374 fixed download drop-down
  assets/css/editor.css
Labels: Easy, PR: unreviewed, SWoC2021

#379 Create new_file
  new_file
Labels: PR: unreviewed

#380 Deleting file
  new_file
Labels: PR: unreviewed

#337 Issue #293 fixed
  assets/css/style.css
  assets/images/spinner.gif
  index.html
Labels: DWOC, Level-4, PR: unreviewed

#382 Removed hove effect from navbar
  assets/css/style.css
Labels: Easy, SWoC2021

#384 Open source programs updated
  README.md
  assets/Readme_assets/hacktoberfest.png
  assets/Readme_assets/psoc.PNG
  assets/Readme_assets/swoc.PNG
Labels: PR: unreviewed

#391 Update README.md with proper repository name #390
  README.md
  assets/Readme_assets/CloneRepo.png
Labels: Beginner, SWoC2021

#363 Add footer in REACT #351 fixed
  .eslintcache
  .gitignore
  package-lock.json
  package.json
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
Labels: Level-4, SWoC2021

#387 Added interactive feedback section in contact us form and improved code for the same
  assets/css/style.css
  assets/images/hand.gif
  index.html
Labels: Medium, SWoC2021

#386 REACT: Added Home Page
  package-lock.json
  package.json
  public/images/events/SLOP.png
  public/images/events/SWOC-logo.png
  public/images/events/hakin_codes.png
  public/images/events/psoc_logo.png
  public/images/events/woc-logo.png
  public/images/team/anush_bhatia.png
  public/images/team/smaranjit_ghose.png
  public/index.html
  src/assests/images/team/anush_bhatia.png
  src/assests/images/team/smaranjit_ghose.png
  src/index.css
  src/pages/HomePage/About/About.js
  src/pages/HomePage/About/About.module.css
  src/pages/HomePage/About/open-source.svg
  src/pages/HomePage/About/step1.svg
  src/pages/HomePage/About/step2.svg
  src/pages/HomePage/About/step3.svg
  src/pages/HomePage/About/step4.svg
  src/pages/HomePage/ContactUs/ContactUs.js
  src/pages/HomePage/ContactUs/ContactUs.module.css
  src/pages/HomePage/Footer/Footer.js
  src/pages/HomePage/Footer/Footer.module.css
  src/pages/HomePage/Header/Header.js
  src/pages/HomePage/Header/Header.module.css
  src/pages/HomePage/Header/logo.png
  src/pages/HomePage/Home/Home.js
  src/pages/HomePage/Home/Home.module.css
  src/pages/HomePage/Home/pen.svg
  src/pages/HomePage/Home/wave.png
  src/pages/HomePage/HomePage.js
  src/pages/HomePage/OpenSource/OpenSource.js
  src/pages/HomePage/OpenSource/OpenSource.module.css
  src/pages/HomePage/SupportUs/Support.module.css
  src/pages/HomePage/SupportUs/SupportUs.js
  src/pages/HomePage/Team/Team.js
  src/pages/HomePage/Team/Team.module.css
Labels: DWOC, Hard, Level-5, PR: unreviewed, SWoC2021

#392 navigation bar added in header
  src/App.js
  src/components/Header/Header.css
  src/components/Header/Header.js
Labels: PR: unreviewed

#411 Added Newsletter in footer
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
Labels: PR: unreviewed

#416 React: Added Word Count
  src/pages/Editor/sections/OutputComponent/Output.js
Labels: Medium, SWoC2021

#420 Routing/418
  package-lock.json
  package.json
  src/App.js
  src/components/Footer/Footer.js
  src/components/Header/Header.js
  src/components/Header/Header.module.css
  src/index.css
  src/pages/Editor/index.js
  src/pages/Home/index.js
  src/pages/Home/sections/About/About.js
  src/pages/Home/sections/Banner/Banner.js
  src/pages/Home/sections/Banner/Banner.module.css
  src/pages/Home/sections/ContactUs/ContactUs.js
  src/pages/Home/sections/SupportUs/SupportUs.js
  src/pages/Home/sections/SupportUs/SupportUs.module.css
  src/pages/Home/sections/Team/Team.js
Labels: PR: unreviewed

#421 [React] Sketch Page Added
  src/App.js
  src/components/Header/Header.js
  src/pages/Sketch/Sketch.js
  src/pages/Sketch/Sketch.module.css
  src/pages/Sketch/components/Canvas.js
  src/pages/Sketch/components/Canvas.module.css
Labels: PR: unreviewed

#425 [React] Font Colors Dropdown in Editor
  src/components/Dropdown/Dropdown.js
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.js
  src/pages/Editor/sections/Settings/Settings.js
Labels: PR: unreviewed

#419 Added back to Top button & DropDown on hover effect
  assets/css/editor.css
  assets/css/style.css
  editor.html
  index.html
Labels: Medium, PR: reviewed-approved, SWoC2021

#423 Controlpanel
  src/components/Dropdown/Dropdown.css
  src/components/Dropdown/Dropdown.js
  src/pages/Editor/components/Slider/NumberSlider.js
  src/pages/Editor/components/Slider/Slider.css
  src/pages/Editor/components/Slider/Slider.js
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/index.js
  src/pages/Editor/sections/Settings/Settings.css
  src/pages/Editor/sections/Settings/Settings.js
  src/pages/Editor/sections/Settings/Settings.module.css
Labels: Hard, PR: partially-approved, SWoC2021

#426 preloader implemented
  src/App.js
  src/components/Preloader/Preloader.jsx
  src/components/Preloader/Preloader.module.css
Labels: DWOC, SWoC2021

#430 Issue#356 Solved Background sheet change
  src/pages/Editor/containers/editContext.js
  src/pages/Editor/sections/OutputComponent/Output.js
Labels: Easy, PR: partially-approved, SWoC2021
